---

- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Create log directory
  file:
    state: directory
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
    recurse: yes
    path: "{{ deployer_root_path }}/{{ deployer_application }}/shared/{{ item }}"
  with_items:
    - log
    - pids
    - configs

- set_fact:
    release_path: "{{ deployer_root_path }}/{{ deployer_application }}/releases/{{ timestamp.stdout }}"

- name: Create release directory
  file:
    state: directory
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
    recurse: yes
    path: "{{ item }}"
  with_items:
    - "{{ release_path }}"

- name: checkout git repo into release directory
  git:
    repo: "{{ deployer_repo }}"
    dest: "{{ release_path }}"
    version: "{{ deployer_branch }}"
  sudo_user: "{{ deployer_rails.user }}"

- name: Create tmp directory
  file:
    state: directory
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
    recurse: yes
    path: "{{ item }}"
  with_items:
    - "{{ release_path }}/tmp"

- name: link directories to current
  file:
    state: link
    path: "{{ release_path }}/{{ item }}"
    src: "{{ deployer_root_path }}/{{ deployer_application }}/shared/{{ item }}"
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
    force: yes
  with_items:
    - log
    - pids
  sudo_user: "{{ deployer_rails.user }}"

- name: link directories to current
  file:
    state: link
    path: "{{ release_path }}/tmp/{{ item }}"
    src: "{{ deployer_root_path }}/{{ deployer_application }}/shared/{{ item }}"
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
    force: yes
  with_items:
    - log
    - pids
  sudo_user: "{{ deployer_rails.user }}"

- name: copy configs
  copy:
    src: "configs/{{ deployer_application }}/"
    dest: "{{ deployer_root_path }}/{{ deployer_application }}/shared/configs/"
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
  sudo_user: "{{ deployer_rails.user }}"

- name: link configs
  file:
    state: link
    force: yes
    dest: "{{ release_path }}/config/{{ item }}"
    src: "{{ deployer_root_path }}/{{ deployer_application }}/shared/configs/{{ item }}"
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"
  with_items: deployer_config_files
  sudo_user: "{{ deployer_rails.user }}"
  when: deployer_config_files is defined

- name: Update app version
  file:
    state: link
    force: yes
    path: "{{ deployer_root_path }}/{{ deployer_application }}/current"
    src: "{{ release_path }}"
    owner: "{{ deployer_rails.user }}"
    group: "{{ deployer_rails.group }}"

- name: set ruby version
  alternatives:
    name: ruby
    path: /usr/bin/ruby{% if deployer_ruby_version == '1.9.3' %}1.9.1{% else %}{{ deployer_ruby_version }}{% endif %}
  when: deployer_ruby_version is defined

- name: set gems version
  alternatives:
    name: gem
    path: /usr/bin/gem{% if deployer_ruby_version == '1.9.3' %}1.9.1{% else %}{{ deployer_ruby_version }}{% endif %}
  when: deployer_ruby_version is defined

- name: update gems
  shell: "bundle install --path {{ deployer_root_path }}/{{ deployer_application }}/shared/bundle --jobs {{ ansible_processor_count }} --without test development --deployment --quiet"
  args:
    chdir: "{{ release_path }}"
  environment: "{{ deployer_env }}"
  sudo_user: "{{ deployer_rails.user }}"


- name: check rake tasks
  shell: "bundle exec rake -T 2>/dev/null"
  args:
    chdir: "{{ release_path }}"
  environment: "{{ deployer_env }}"
  sudo_user: "{{ deployer_rails.user }}"
  register: rake_tasks
  failed_when: False
  changed_when: False

- name: precompile assets
  shell: "RAILS_GROUPS=assets bundle exec rake assets:precompile"
  args:
    chdir: "{{ release_path }}"
  environment: "{{ deployer_env }}"
  sudo_user: "{{ deployer_rails.user }}"
  when: '"assets:precompile" in rake_tasks.stdout'

- name: remove new relic file
  file:
    path: "{{ release_path}}/config/newrelic.yml"
    state: absent

- lineinfile:
    dest: /etc/environment
    state: absent 
    regexp: "^export GITHUB_PARTYFOUL_TOKEN=.*"

- name: remove older releases
  shell: "ls -t1 | tail -n +4 | xargs rm -r"
  ignore_errors: true
  args:
    chdir: "{{ deployer_root_path }}/{{ deployer_application }}/releases/"

- name: restart passenger
  file:
    path: "{{ release_path }}/tmp/restart.txt"
    state: touch
  sudo_user: "{{ deployer_rails.user }}"

- name: restart services
  service: 
    name: "{{ item }}"
    state: restarted
  with_items: deployer_services
  ignore_errors: true
